version: '3.8'

services:
  stride-app:
    build:
      context: .
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "8080:8080"
    volumes:
      - ./stride.db:/app/stride.db
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
